name: plating_mobile_app
description: "Plating hybrid webview application for iOS and Android"
publish_to: 'none'

version: 1.0.0+59

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  photo_manager: 3.0.0
  image_picker: ^1.1.2
  http: ^1.2.1
  image: ^4.1.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  firebase_analytics: ^12.3.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon_adaptive_foreground.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/splash_icon.png"
  android: true
  ios: true
